---
- hosts: all
  tasks:
    - name: install httpd
      package: name=httpd state=installed
    - name: configure
      shell: "echo Welcome to Ojasvi Server - Salesforce Training  > /var/www/html/index.html"
    - name: start service
      service: name=httpd state=started
    - name: add user
      user: name=Ojasvi state=present
